import path from 'path';
import fs from 'fs';
import type { TestInfo } from '@playwright/test';

export type LegacyOperationalDataSource = 'entities' | 'base';
export type LegacyOperationalDataSourceInput = LegacyOperationalDataSource | 'base-entities';

export interface LegacyOperationalDataLookupContext {
    browserName: string;
    env: string;
    lookupKey: string;
    requestedSource: string;
    normalizedSource: LegacyOperationalDataSource;
    runId: string | null;
    runIdSuffix: string;
    seedCommand: string;
}

export interface LegacyOperationalDataCandidate extends LegacyOperationalDataLookupContext {
    filename: string;
    isPrimary: boolean;
    path: string;
    priority: number;
    source: LegacyOperationalDataSource;
}

/**
 * DataPathHelper - Unified Data Path Management
 *
 * Provides centralized logic for generating data file paths
 * for test execution.
 */
export class DataPathHelper {
    private static ensureDataDir(): string {
        const dirPath = path.join(process.cwd(), 'playwright', '.data');
        if (!fs.existsSync(dirPath)) {
            fs.mkdirSync(dirPath, { recursive: true });
        }
        return dirPath;
    }

    private static getEnvName(): string {
        return (process.env.ENV || 'QA').toLowerCase();
    }

    private static getLegacyRunId(): string | null {
        const rawRunId = (process.env.LEGACY_RUN_ID || '').trim();
        if (!rawRunId) return null;

        const sanitized = rawRunId
            .toLowerCase()
            .replace(/[^a-z0-9_-]+/g, '-')
            .replace(/^-+|-+$/g, '');

        return sanitized || null;
    }

    private static getLegacyRunIdSuffix(): string {
        const runId = this.getLegacyRunId();
        return runId ? `-${runId}` : '';
    }

    private static buildDataPath(filename: string): string {
        return path.join(this.ensureDataDir(), filename);
    }

    /**
     * Map project names to consistent browser identifiers
     * This ensures that base-entities-chromium and chromium use the same data file
     */
    private static readonly PROJECT_TO_BROWSER: Record<string, string> = {
        'seed-transportista-chromium': 'chromium',
        'base-entities-chromium': 'chromium',
        'chromium': 'chromium',
    };

    /**
     * Get browser-specific config setup data path.
     *
     * @param testInfo - Playwright TestInfo object containing project metadata
     * @returns Absolute path like: /path/to/project/playwright/.data/setup-config-data-qa.json
     *
     * @example
     * ```typescript
     * test('My test', async ({ page }, testInfo) => {
     *   const dataPath = DataPathHelper.getSetupConfigDataPath(testInfo);
     *   // Result: /project/playwright/.data/setup-config-data-qa.json
     * });
     * ```
     */
    static getSetupConfigDataPath(testInfo: TestInfo): string {
        const env = this.getEnvName();
        const filename = `setup-config-data-${env}.json`;
        return this.buildDataPath(filename);
    }

    /**
     * Backward-compatible alias for setup config data.
     * Use getSetupConfigDataPath() for new config/setup code.
     */
    static getWorkerDataPath(testInfo: TestInfo): string {
        return this.getSetupConfigDataPath(testInfo);
    }

    /**
     * Data generated by legacy entity tests:
     * transportistas-crear, cliente-crear, conductor-crear, vehiculo-crear.
     * Optional suffix with LEGACY_RUN_ID for run-level isolation.
     */
    static getLegacyEntityDataPath(testInfo: TestInfo): string {
        const env = this.getEnvName();
        const runIdSuffix = this.getLegacyRunIdSuffix();
        return this.buildDataPath(`legacy-entities-data-${env}${runIdSuffix}.json`);
    }

    /**
     * Data generated by base-entities.setup.ts.
     * Optional suffix with LEGACY_RUN_ID for run-level isolation.
     */
    static getLegacyBaseDataPath(testInfo: TestInfo): string {
        const env = this.getEnvName();
        const runIdSuffix = this.getLegacyRunIdSuffix();
        return this.buildDataPath(`legacy-base-entities-data-${env}${runIdSuffix}.json`);
    }

    /**
     * Selector for operational tests (contratos/viajes/prefactura/ultimamilla).
     * LEGACY_DATA_SOURCE options:
     * - entities (default): consume legacy-entities-data-*.json
     * - base: consume legacy-base-entities-data-*.json
     * Optional LEGACY_RUN_ID is honored by both sources.
     */
    static getLegacyOperationalDataPath(testInfo: TestInfo): string {
        const source = this.normalizeLegacyDataSource();
        if (source === 'base') {
            return this.getLegacyBaseDataPath(testInfo);
        }
        return this.getLegacyEntityDataPath(testInfo);
    }

    static normalizeLegacyDataSource(source = process.env.LEGACY_DATA_SOURCE): LegacyOperationalDataSource {
        const normalizedSource = (source || 'entities').trim().toLowerCase();
        return normalizedSource === 'base' || normalizedSource === 'base-entities'
            ? 'base'
            : 'entities';
    }

    static getLegacyOperationalSeedCommand(source = process.env.LEGACY_DATA_SOURCE): string {
        const envPrefix = this.getEnvName() === 'demo' ? 'demo' : 'qa';
        return this.normalizeLegacyDataSource(source) === 'base'
            ? `npm run ${envPrefix}:seed:legacy`
            : `npm run ${envPrefix}:regression:entities`;
    }

    static getLegacyOperationalDataLookupContext(
        testInfo: TestInfo,
        source = process.env.LEGACY_DATA_SOURCE
    ): LegacyOperationalDataLookupContext {
        const browserName = this.getBrowserName(testInfo);
        const env = this.getEnvName();
        const runId = this.getLegacyRunId();
        const runIdSuffix = runId ? `-${runId}` : '';
        const requestedSource = (source || 'entities').trim().toLowerCase() || 'entities';

        return {
            browserName,
            env,
            lookupKey: `${env}:${runId || 'default'}`, // Removed browserName from lookupKey
            normalizedSource: this.normalizeLegacyDataSource(source),
            requestedSource,
            runId,
            runIdSuffix,
            seedCommand: this.getLegacyOperationalSeedCommand(source)
        };
    }

    static getLegacyOperationalDataCandidates(
        testInfo: TestInfo,
        source = process.env.LEGACY_DATA_SOURCE
    ): LegacyOperationalDataCandidate[] {
        const context = this.getLegacyOperationalDataLookupContext(testInfo, source);
        const orderedSources: LegacyOperationalDataSource[] = context.normalizedSource === 'base'
            ? ['base', 'entities']
            : ['entities', 'base'];

        return orderedSources.map((candidateSource, index) => {
            const filename = candidateSource === 'base'
                ? `legacy-base-entities-data-${context.env}${context.runIdSuffix}.json`
                : `legacy-entities-data-${context.env}${context.runIdSuffix}.json`;

            return {
                ...context,
                filename,
                isPrimary: index === 0,
                path: this.buildDataPath(filename),
                priority: index,
                source: candidateSource
            };
        });
    }

    /**
     * Candidate paths for operational data, prioritizing the configured source
     * and then falling back to the alternate legacy source.
     *
     * This keeps deterministic source selection while still allowing operational
     * smoke flows to recover explicitly when the preferred seed artifact was not
     * generated for the current browser/environment.
     */
    static getLegacyOperationalDataCandidatePaths(testInfo: TestInfo): string[] {
        return this.getLegacyOperationalDataCandidates(testInfo).map((candidate) => candidate.path);
    }

    /**
     * Canonical setup artifact path requested by the Carga seeding flow.
     * Output filename is fixed as "carga_setup_data.json".
     */
    static getCargaSetupDataPath(): string {
        return this.buildDataPath('carga_setup_data.json');
    }

    /**
     * Worker/browser isolated setup artifact path to avoid collisions
     * when setup is executed in parallel projects.
     */
    static getScopedCargaSetupDataPath(testInfo: TestInfo): string {
        const env = this.getEnvName();
        return this.buildDataPath(`carga_setup_data-${env}.json`);
    }

    /**
     * Get project identifier (browser name)
     *
     * @param testInfo - Playwright TestInfo object
     * @returns Project name
     */
    static getProjectIdentifier(testInfo: TestInfo): string {
        return testInfo.project.name;
    }

    /**
     * Get worker index for logging and debugging
     *
     * @param testInfo - Playwright TestInfo object
     * @returns Worker index (0, 1, 2, etc.)
     */
    static getWorkerIndex(testInfo: TestInfo): number {
        return testInfo.workerIndex;
    }

    /**
     * Get browser name from project name
     *
     * @param testInfo - Playwright TestInfo object
     * @returns Browser name: 'chromium' or 'default'
     */
    static getBrowserName(testInfo: TestInfo): string {
        const projectName = testInfo.project.name.toLowerCase();
        if (projectName.includes('chromium')) return 'chromium';
        return this.PROJECT_TO_BROWSER[projectName] || 'default';
    }
}
