import path from 'path';
import fs from 'fs';
import { TestInfo } from '@playwright/test';

/**
 * DataPathHelper - Browser-Isolated Data Path Management
 *
 * Provides centralized logic for generating browser-specific data file paths
 * to enable safe parallel test execution across multiple browsers.
 *
 * Each browser project gets its own isolated JSON file:
 * - Chromium projects -> setup-config-data-chromium-{env}.json
 * - Firefox projects  -> setup-config-data-firefox-{env}.json
 * - Webkit projects   -> setup-config-data-webkit-{env}.json
 *
 * This prevents data collisions when running tests in parallel.
 */
export class DataPathHelper {
    private static ensureDataDir(): string {
        const dirPath = path.join(process.cwd(), 'playwright', '.data');
        if (!fs.existsSync(dirPath)) {
            fs.mkdirSync(dirPath, { recursive: true });
        }
        return dirPath;
    }

    private static getEnvName(): string {
        return (process.env.ENV || 'QA').toLowerCase();
    }

    private static getLegacyRunIdSuffix(): string {
        const rawRunId = (process.env.LEGACY_RUN_ID || '').trim();
        if (!rawRunId) return '';

        const sanitized = rawRunId
            .toLowerCase()
            .replace(/[^a-z0-9_-]+/g, '-')
            .replace(/^-+|-+$/g, '');

        return sanitized ? `-${sanitized}` : '';
    }

    private static buildDataPath(filename: string): string {
        return path.join(this.ensureDataDir(), filename);
    }

    /**
     * Map project names to consistent browser identifiers
     * This ensures that base-entities-chromium and chromium use the same data file
     */
    private static readonly PROJECT_TO_BROWSER: Record<string, string> = {
        // Seed transportista projects
        'seed-transportista-chromium': 'chromium',
        'seed-transportista-firefox': 'firefox',

        // Base entities setup projects
        'base-entities-chromium': 'chromium',
        'base-entities-firefox': 'firefox',
        'base-entities-webkit': 'webkit',

        // Test projects
        'chromium': 'chromium',
        'firefox': 'firefox',
        'webkit': 'webkit',
    };

    /**
     * Get browser-specific config setup data path.
     *
     * @param testInfo - Playwright TestInfo object containing project metadata
     * @returns Absolute path like: /path/to/project/playwright/.data/setup-config-data-chromium-qa.json
     *
     * @example
     * ```typescript
     * test('My test', async ({ page }, testInfo) => {
     *   const dataPath = DataPathHelper.getSetupConfigDataPath(testInfo);
     *   // chromium/base-entities-chromium: /project/playwright/.data/setup-config-data-chromium-qa.json
     *   // firefox/base-entities-firefox:   /project/playwright/.data/setup-config-data-firefox-qa.json
     * });
     * ```
     */
    static getSetupConfigDataPath(testInfo: TestInfo): string {
        const browserName = this.getBrowserName(testInfo);
        const env = this.getEnvName();
        const filename = `setup-config-data-${browserName}-${env}.json`;
        return this.buildDataPath(filename);
    }

    /**
     * Backward-compatible alias for setup config data.
     * Use getSetupConfigDataPath() for new config/setup code.
     */
    static getWorkerDataPath(testInfo: TestInfo): string {
        return this.getSetupConfigDataPath(testInfo);
    }

    /**
     * Data generated by legacy entity tests:
     * transportistas-crear, cliente-crear, conductor-crear, vehiculo-crear.
     * Optional suffix with LEGACY_RUN_ID for run-level isolation.
     */
    static getLegacyEntityDataPath(testInfo: TestInfo): string {
        const browserName = this.getBrowserName(testInfo);
        const env = this.getEnvName();
        const runIdSuffix = this.getLegacyRunIdSuffix();
        return this.buildDataPath(`legacy-entities-data-${browserName}-${env}${runIdSuffix}.json`);
    }

    /**
     * Data generated by base-entities.setup.ts.
     * Optional suffix with LEGACY_RUN_ID for run-level isolation.
     */
    static getLegacyBaseDataPath(testInfo: TestInfo): string {
        const browserName = this.getBrowserName(testInfo);
        const env = this.getEnvName();
        const runIdSuffix = this.getLegacyRunIdSuffix();
        return this.buildDataPath(`legacy-base-entities-data-${browserName}-${env}${runIdSuffix}.json`);
    }

    /**
     * Selector for operational tests (contratos/viajes/prefactura/ultimamilla).
     * LEGACY_DATA_SOURCE options:
     * - entities (default): consume legacy-entities-data-*.json
     * - base: consume legacy-base-entities-data-*.json
     * Optional LEGACY_RUN_ID is honored by both sources.
     */
    static getLegacyOperationalDataPath(testInfo: TestInfo): string {
        const source = (process.env.LEGACY_DATA_SOURCE || 'entities').toLowerCase();
        if (source === 'base' || source === 'base-entities') {
            return this.getLegacyBaseDataPath(testInfo);
        }
        return this.getLegacyEntityDataPath(testInfo);
    }

    /**
     * Canonical setup artifact path requested by the Carga seeding flow.
     * Output filename is fixed as "carga_setup_data.json".
     */
    static getCargaSetupDataPath(): string {
        return this.buildDataPath('carga_setup_data.json');
    }

    /**
     * Worker/browser isolated setup artifact path to avoid collisions
     * when setup is executed in parallel projects.
     */
    static getScopedCargaSetupDataPath(testInfo: TestInfo): string {
        const env = this.getEnvName();
        const browser = this.getBrowserName(testInfo);
        return this.buildDataPath(`carga_setup_data-${browser}-${env}.json`);
    }

    /**
     * Get project identifier (browser name)
     *
     * @param testInfo - Playwright TestInfo object
     * @returns Browser name: 'chromium', 'firefox', 'webkit', etc.
     *
     * @example
     * ```typescript
     * const browser = DataPathHelper.getProjectIdentifier(testInfo);
     * // Returns: 'chromium', 'firefox', or 'webkit'
     * ```
     */
    static getProjectIdentifier(testInfo: TestInfo): string {
        return testInfo.project.name;
    }

    /**
     * Get worker index for logging and debugging
     *
     * @param testInfo - Playwright TestInfo object
     * @returns Worker index (0, 1, 2, etc.)
     */
    static getWorkerIndex(testInfo: TestInfo): number {
        return testInfo.workerIndex;
    }

    /**
     * Get browser name from project name
     *
     * @param testInfo - Playwright TestInfo object
     * @returns Browser name: 'chromium', 'firefox', 'webkit', or 'default'
     */
    static getBrowserName(testInfo: TestInfo): string {
        const projectName = testInfo.project.name.toLowerCase();
        if (projectName.includes('chromium')) return 'chromium';
        if (projectName.includes('firefox')) return 'firefox';
        if (projectName.includes('webkit')) return 'webkit';
        return this.PROJECT_TO_BROWSER[projectName] || 'default';
    }
}
